# typed: false
# frozen_string_literal: true

# This file was generated by a script. Do not edit manually.
# Source: https://github.com/ahmed-abdelgawad92/lockify

class Lockify < Formula
  desc "Secure environment variable management"
  homepage "https://github.com/ahmed-abdelgawad92/lockify"
  url "{{TARBALL_URL}}"
  sha256 "{{SHA256}}"
  license "MIT"
  head "https://github.com/ahmed-abdelgawad92/lockify.git", branch: "main"

  depends_on "go" => :build

  def install
    ENV["CGO_ENABLED"] = "0"
    
    ldflags = %W[
      -s -w
      -X github.com/ahmed-abdelgawad92/lockify/cmd.Version=#{version}
    ].join(" ")

    system "go", "build", *std_go_args(ldflags:), "./main.go"
  end

  test do
    assert_match "Lockify CLI v#{version}", shell_output("#{bin}/lockify version 2>&1")
  end
end

